AllCops:
  NewCops: enable
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**.*'
